# Generated by Django 2.2.7 on 2020-12-22 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Act', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField(blank=True, db_column='image_base64')),
                ('period', models.DateTimeField(blank=True, db_column='period', db_index=True, default=datetime.datetime.now)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='Act.Notification')),
            ],
            options={
                'db_table': 'ScreenImage',
            },
        ),
    ]
